(cl:defpackage sauavs-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "VEC4"
   "<VEC4-REQUEST>"
   "VEC4-REQUEST"
   "<VEC4-RESPONSE>"
   "VEC4-RESPONSE"
  ))

