// Generated by gencpp from file sauavs/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SAUAVS_MESSAGE_ADDTWOINTS_H
#define SAUAVS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sauavs/AddTwoIntsRequest.h>
#include <sauavs/AddTwoIntsResponse.h>


namespace sauavs
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sauavs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sauavs::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sauavs::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sauavs::AddTwoInts > {
  static const char* value()
  {
    return "sauavs/AddTwoInts";
  }

  static const char* value(const ::sauavs::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sauavs::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::sauavs::AddTwoInts >
template<>
struct MD5Sum< ::sauavs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sauavs::AddTwoInts >::value();
  }
  static const char* value(const ::sauavs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sauavs::AddTwoIntsRequest> should match
// service_traits::DataType< ::sauavs::AddTwoInts >
template<>
struct DataType< ::sauavs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sauavs::AddTwoInts >::value();
  }
  static const char* value(const ::sauavs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sauavs::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::sauavs::AddTwoInts >
template<>
struct MD5Sum< ::sauavs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sauavs::AddTwoInts >::value();
  }
  static const char* value(const ::sauavs::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sauavs::AddTwoIntsResponse> should match
// service_traits::DataType< ::sauavs::AddTwoInts >
template<>
struct DataType< ::sauavs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sauavs::AddTwoInts >::value();
  }
  static const char* value(const ::sauavs::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAUAVS_MESSAGE_ADDTWOINTS_H
