// Generated by gencpp from file sauavs/Vec4Response.msg
// DO NOT EDIT!


#ifndef SAUAVS_MESSAGE_VEC4RESPONSE_H
#define SAUAVS_MESSAGE_VEC4RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sauavs
{
template <class ContainerAllocator>
struct Vec4Response_
{
  typedef Vec4Response_<ContainerAllocator> Type;

  Vec4Response_()
    : success(false)
    , message()  {
    }
  Vec4Response_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::sauavs::Vec4Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sauavs::Vec4Response_<ContainerAllocator> const> ConstPtr;

}; // struct Vec4Response_

typedef ::sauavs::Vec4Response_<std::allocator<void> > Vec4Response;

typedef boost::shared_ptr< ::sauavs::Vec4Response > Vec4ResponsePtr;
typedef boost::shared_ptr< ::sauavs::Vec4Response const> Vec4ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sauavs::Vec4Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sauavs::Vec4Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sauavs::Vec4Response_<ContainerAllocator1> & lhs, const ::sauavs::Vec4Response_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sauavs::Vec4Response_<ContainerAllocator1> & lhs, const ::sauavs::Vec4Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sauavs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sauavs::Vec4Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauavs::Vec4Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauavs::Vec4Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauavs::Vec4Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauavs::Vec4Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauavs::Vec4Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sauavs::Vec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::sauavs::Vec4Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::sauavs::Vec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sauavs/Vec4Response";
  }

  static const char* value(const ::sauavs::Vec4Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sauavs::Vec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::sauavs::Vec4Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sauavs::Vec4Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vec4Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sauavs::Vec4Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sauavs::Vec4Response_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAUAVS_MESSAGE_VEC4RESPONSE_H
