// Generated by gencpp from file sauavs/Vec4Request.msg
// DO NOT EDIT!


#ifndef SAUAVS_MESSAGE_VEC4REQUEST_H
#define SAUAVS_MESSAGE_VEC4REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sauavs
{
template <class ContainerAllocator>
struct Vec4Request_
{
  typedef Vec4Request_<ContainerAllocator> Type;

  Vec4Request_()
    : goal()  {
      goal.assign(0.0);
  }
  Vec4Request_(const ContainerAllocator& _alloc)
    : goal()  {
  (void)_alloc;
      goal.assign(0.0);
  }



   typedef boost::array<double, 4>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::sauavs::Vec4Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sauavs::Vec4Request_<ContainerAllocator> const> ConstPtr;

}; // struct Vec4Request_

typedef ::sauavs::Vec4Request_<std::allocator<void> > Vec4Request;

typedef boost::shared_ptr< ::sauavs::Vec4Request > Vec4RequestPtr;
typedef boost::shared_ptr< ::sauavs::Vec4Request const> Vec4RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sauavs::Vec4Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sauavs::Vec4Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sauavs::Vec4Request_<ContainerAllocator1> & lhs, const ::sauavs::Vec4Request_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sauavs::Vec4Request_<ContainerAllocator1> & lhs, const ::sauavs::Vec4Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sauavs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sauavs::Vec4Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauavs::Vec4Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauavs::Vec4Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauavs::Vec4Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauavs::Vec4Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauavs::Vec4Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sauavs::Vec4Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c0f8a43662c8b5ae9791fef095791e5";
  }

  static const char* value(const ::sauavs::Vec4Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c0f8a43662c8b5aULL;
  static const uint64_t static_value2 = 0xe9791fef095791e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::sauavs::Vec4Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sauavs/Vec4Request";
  }

  static const char* value(const ::sauavs::Vec4Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sauavs::Vec4Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[4] goal\n"
;
  }

  static const char* value(const ::sauavs::Vec4Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sauavs::Vec4Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vec4Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sauavs::Vec4Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sauavs::Vec4Request_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAUAVS_MESSAGE_VEC4REQUEST_H
