// Generated by gencpp from file sauavs/Vec4.msg
// DO NOT EDIT!


#ifndef SAUAVS_MESSAGE_VEC4_H
#define SAUAVS_MESSAGE_VEC4_H

#include <ros/service_traits.h>


#include <sauavs/Vec4Request.h>
#include <sauavs/Vec4Response.h>


namespace sauavs
{

struct Vec4
{

typedef Vec4Request Request;
typedef Vec4Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Vec4
} // namespace sauavs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sauavs::Vec4 > {
  static const char* value()
  {
    return "023f7b397f1175bc8ddb57928281c1d4";
  }

  static const char* value(const ::sauavs::Vec4&) { return value(); }
};

template<>
struct DataType< ::sauavs::Vec4 > {
  static const char* value()
  {
    return "sauavs/Vec4";
  }

  static const char* value(const ::sauavs::Vec4&) { return value(); }
};


// service_traits::MD5Sum< ::sauavs::Vec4Request> should match
// service_traits::MD5Sum< ::sauavs::Vec4 >
template<>
struct MD5Sum< ::sauavs::Vec4Request>
{
  static const char* value()
  {
    return MD5Sum< ::sauavs::Vec4 >::value();
  }
  static const char* value(const ::sauavs::Vec4Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::sauavs::Vec4Request> should match
// service_traits::DataType< ::sauavs::Vec4 >
template<>
struct DataType< ::sauavs::Vec4Request>
{
  static const char* value()
  {
    return DataType< ::sauavs::Vec4 >::value();
  }
  static const char* value(const ::sauavs::Vec4Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sauavs::Vec4Response> should match
// service_traits::MD5Sum< ::sauavs::Vec4 >
template<>
struct MD5Sum< ::sauavs::Vec4Response>
{
  static const char* value()
  {
    return MD5Sum< ::sauavs::Vec4 >::value();
  }
  static const char* value(const ::sauavs::Vec4Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::sauavs::Vec4Response> should match
// service_traits::DataType< ::sauavs::Vec4 >
template<>
struct DataType< ::sauavs::Vec4Response>
{
  static const char* value()
  {
    return DataType< ::sauavs::Vec4 >::value();
  }
  static const char* value(const ::sauavs::Vec4Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAUAVS_MESSAGE_VEC4_H
